[book]
authors = ["cyraivndle2"]
language = "zh"
multilingual = false
src = "src"
title = "非对称加密教程（GPG 教程）"
description = "面向初学者的非对称加密教程，讲解非对称加密的基本概念和流程，提供非对称加密软件 Kleopatra（GnuPG/Gpg4win）和OpenKeychain 的图文使用教程。"

[build]
create-missing = false

[output.html]
git-repository-url = "https://github.com/cyraivndle2/gpg-tutorial"
additional-js = ["vendor/cjk-search/fzf.umd.js", "vendor/cjk-search/elasticlunr.js"]